config/routes.rb
Rails.application.routes.draw do
  #get 'users/new'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.htm
  # Defines the root path route ("/")
  get "/tests", to: "orders#tests"
  get "/tables-for-n-upto-m/:n/:m", to: "articles#tables"
  get "/db_design", to: "articles#db_design"
  get "/tables2-n-upto-m", to: "articles#tables2" 
  get "/signup", to: "users#new", as: "signup"  
  get "/users/:id" => "users#show"
  post "/users", to: "users#create", as: "users"
  get "/login", to: "sessions#new", as: "login"
  post "/create", to: "sessions#create", as: "create"
  delete "/logout", to: "sessions#destroy", as: "logout"
 
  root "articles#index"
  resources :articles do
    resources :comments 
  end
  resources :orders   do
    resources :customers
  end
  resources :banks
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments
  validates_associated :comments
  validates :title, presence: true
  validates :body, presence: true
  validates :number, numericality: true
end

app/models/bank.rb
class Bank < ApplicationRecord
  validates :name, :lastname, presence: true
  validates :email,  presence: true, uniqueness: true
  validates :city, presence: true
  validates :pin, numericality: true
  validates :age, numericality: { only_integer: true }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/country.rb
class Country < ApplicationRecord
  has_many :user
end

app/models/employee.rb
class Employee < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  validates :name, presence: true
  validates :lastname,  presence: true
  validates :email,  confirmation: true
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :country
  before_save { self.email = email.downcase }
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, length: { in: 6..10 }
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to root_path, status: :see_other
  end

  def tables
    @n = params[:n].to_i
  end

  def tables2
    @n = params[:n].to_i
  end

  def db_design
  end

  def home
  end
  private
  def article_params
    params.require(:article).permit(:title, :body)
  end
end

app/controllers/banks_controller.rb
class BanksController < ApplicationController
  layout "banks"
  def index 
    @banks = Bank.all
  end
  
  def show
    @bank = Bank.find(params[:id])
  end 

  def new
    @bank = Bank.new  
  end

  def create
    @bank = Bank.new(bank_params)
    respond_to do |format|
      if @bank.save 
        BankMailer.with(bank: @bank).welcome_email.deliver_later
        format.html {redirect_to @bank}
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @bank = Bank.find(params[:id])
  end

  def update
    @bank = Bank.find(params[:id])
    if @bank.update(bank_params)
      redirect_to @bank
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @bank = Bank.find(params[:id])
    @bank.destroy
    respond_to do |format|
      format.html { redirect_to banks_url, notice: "Bank was successfully destroyed." }
    end
  end

  private
  def bank_params
    params.require(:bank).permit(:name, :lastname, :email, :city, :pin, :age)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  #http_basic_authenticate_with name: "dhh", password: "secret", only: :destroy

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end


  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article),:show, status: :see_other
  end

  private
  def comment_params
    params.require(:comment).permit(:commenter, :body, :status)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = Order.all
  end

  def show
    @order = Order.find(params[:id])
  end

  def new
    @order = Order.new
  end

  def create
    @order = Order.new(order_params)
    if @order.save
      OrderMailer.with(order: @order).new_order_email.deliver_later
      redirect_to @order
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit 
    @order = Order.find(params[:id])
  end

  def update
    @order = Order.find(params[:id])
    if @order.update(order_params)
      redirect_to @order
    else
      render :edit, status: :unprocessable_entity
    end
  end 
  def destroy
    @order = Order.find(params[:id])
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: "Bank was successfully destroyed." }
    end
  end

  def tests
  end

  private
  def order_params
    params.require(:order).permit(:name, :lastname, :status)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    @user = User.find_by(email: params[:session][:email].downcase)
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to '/login'
    else
      flash[:notice] = 'Invalid email/password combination'
      redirect_to articles_url
    end
  end

  def destroy
    session.delete(:user_id)
    @user = nil
    #redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    binding.pry
    @user = User.new
  end

  def show 
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save 
      flash[:messages] = "Successfully create User, please login..."
    else
      flash[:messages] = @user.errors.full_messages.join(', ')
    end
    redirect_to signup_path 
  end

  def countries
    @countries = Country.pluck(:name, :id)
  end 

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :country)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/banks/_empty_list.html.erb
<h1>There are no items in this list <b>yet</b></h1>

app/views/banks/_form.html.erb
<%= form_with model: @bank do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    <% bank.errors.full_messages_for(:name).each do |message| %>
      <div>
        <%= message %>
      </div>
    <% end %>
  </div>

  <div>
    <%= form.label :lastname %><br>
    <%= form.text_field :lastname %><br>
    <% bank.errors.full_messages_for(:lastname).each do |message| %>
      <div>
        <%= message %>
      </div>
    <% end %>
  </div>

  <div>
    <%= form.label :email %><br>
    <%= form.text_field :email %><br>
    <% bank.errors.full_messages_for(:email).each do |message| %>
      <div>
        <%= message %>
      </div>
    <% end %>
  </div>

  <div>
    <%= form.label :city %><br>
    <%= form.text_field :city %><br>
    <% bank.errors.full_messages_for(:city).each do |message| %>
      <div>
        <%= message %>
      </div>
    <% end %>
  </div>

  <div>
    <%= form.label :pin %><br>
    <%= form.password_field :pin %><br>
    <% bank.errors.full_messages_for(:pin).each do |message| %>
      <div>
        <%= message %>
      </div>
    <% end %>
  </div>

  <div>
    <%= form.label :age %><br>
    <%= form.text_field :age %><br>
    <% bank.errors.full_messages_for(:age).each do |message| %>
      <div>
        <%= message %>
      </div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/banks/edit.html.erb
<%= render 'form', bank: @bank %>

app/views/banks/index.html.erb
<table>
  <thead>
    <tr>
      <th>name</th>
      <th>lastname</th>
      <th>Email</th>
      <th>City</th>
      <th>pin</th>
      <th>Age</th>
    </tr>
  </thead>
  <tbody>
    <% @banks.each do |bank| %>
      <tr>
        <td><%= link_to bank.name, bank %></td>
        <td><%= link_to bank.lastname, bank %></td>
        <td><%= link_to bank.email, bank %></td>
        <td><%= link_to bank.city, bank %></td>
        <td><%= link_to bank.pin, bank %></td>
        <td><%= link_to bank.age, bank %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<br>
<div>
  <%= link_to "New bank", new_bank_path %>
</div>

<%= render @bank || "empty_list" %>

app/views/banks/new.html.erb
<%= render partial: 'form', locals: {bank: @bank} %>

<h1 class= "mains">new Banks pages</h1>

app/views/banks/show.html.erb
<h1><%= @bank.name %></h1>
<p><%= @bank.lastname %></p>
<p><%= @bank.email %></p>
<p><%= @bank.city %></p>
<p><%= @bank.pin %></p>
<p style="font-size: 25px"><%= @bank.age %></p>

<ol>
  <li>
    <%= link_to "Edit", edit_bank_path(@bank) %>
  </li>
</ol>

 <%= button_to "Destroy this bank", @bank, method: :delete %>

app/views/orders/_form.html.erb
<%= form_with model: @order do |form| %>

  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :lastname %><br>
    <%= form.text_field :lastname %><br>
  </div>

  <div>
    <%= form.label :email %><br>
    <%= form.text_field :email%><br>
  </div>

  
  <div>
    <%= form.label :status %><br>
    <%= form.select :status, ['public', 'private', 'archived'], selected: 'private' %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Order Edit</h1>

<%= render "form", order: @order %>

app/views/orders/index.html.erb
<h1>Index Order</h1>

<% @orders.each do |order| %>
  <ol>
    <li>
      <%= link_to order.name, order %>
    </li>
    <li>
      <%= link_to order.lastname, order %>
    </li>
    <li>
      <%= link_to order.email, order %>
    </li>
  </ol>
<% end %>
<%= link_to "New order", new_order_path %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render "form", order: @order %>

app/views/orders/show.html.erb
<h1><%= @order.name %></h1>
<p><%= @order.lastname %></p>
<p><%= @order.email %></p>


<ol>
  <li>
    <%= link_to "Edit", edit_order_path(@order) %>
  </li> 
</ol>

 <%= button_to "Destroy this order", @order, method: :delete %>

app/views/orders/tests.html.erb
<p>This is a paragraph</p>