config/routes.rb
Rails.application.routes.draw do
  #get 'users/new'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.htm
  # Defines the root path route ("/")
  get "/tests", to: "orders#tests"
  get "/tables-for-n-upto-m/:n/:m", to: "articles#tables"
  get "/db_design", to: "articles#db_design"
  get "/tables2-n-upto-m", to: "articles#tables2" 
  get "/signup", to: "users#new", as: "signup"  
  get "/users/:id" => "users#show"
  post "/users", to: "users#create", as: "users"
  get "/login", to: "sessions#new", as: "login"
  post "/create", to: "sessions#create", as: "create"
  delete "/logout", to: "sessions#destroy", as: "logout"
 
  root "articles#index"
  resources :articles do
    resources :comments 
  end
  resources :orders   do
    resources :customers
  end
  resources :banks
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments
  validates_associated :comments
  validates :title, presence: true
  validates :body, presence: true
  validates :number, numericality: true
end

app/models/bank.rb
class Bank < ApplicationRecord
  validates :name, :lastname, presence: true
  validates :email,  presence: true, uniqueness: true
  validates :city, presence: true
  validates :pin, numericality: true
  validates :age, numericality: { only_integer: true }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/country.rb
class Country < ApplicationRecord
  has_many :user
end

app/models/employee.rb
class Employee < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  validates :name, presence: true
  validates :lastname,  presence: true
  validates :email,  confirmation: true
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :country
  before_save { self.email = email.downcase }
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, length: { in: 6..10 }
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to root_path, status: :see_other
  end

  def tables
    @n = params[:n].to_i
  end

  def tables2
    @n = params[:n].to_i
  end

  def db_design
  end

  def home
  end
  private
  def article_params
    params.require(:article).permit(:title, :body)
  end
end

app/controllers/banks_controller.rb
class BanksController < ApplicationController
  layout "banks"
  def index 
    @banks = Bank.all
  end
  
  def show
    @bank = Bank.find(params[:id])
  end 

  def new
    @bank = Bank.new  
  end

  def create
    @bank = Bank.new(bank_params)
    respond_to do |format|
      if @bank.save 
        BankMailer.with(bank: @bank).welcome_email.deliver_later
        format.html {redirect_to @bank}
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @bank = Bank.find(params[:id])
  end

  def update
    @bank = Bank.find(params[:id])
    if @bank.update(bank_params)
      redirect_to @bank
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @bank = Bank.find(params[:id])
    @bank.destroy
    respond_to do |format|
      format.html { redirect_to banks_url, notice: "Bank was successfully destroyed." }
    end
  end

  private
  def bank_params
    params.require(:bank).permit(:name, :lastname, :email, :city, :pin, :age)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = Order.all
  end

  def show
    @order = Order.find(params[:id])
  end

  def new
    @order = Order.new
  end

  def create
    @order = Order.new(order_params)
    if @order.save
      OrderMailer.with(order: @order).new_order_email.deliver_later
      redirect_to @order
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit 
    @order = Order.find(params[:id])
  end

  def update
    @order = Order.find(params[:id])
    if @order.update(order_params)
      redirect_to @order
    else
      render :edit, status: :unprocessable_entity
    end
  end 
  def destroy
    @order = Order.find(params[:id])
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: "Bank was successfully destroyed." }
    end
  end

  def tests
  end

  private
  def order_params
    params.require(:order).permit(:name, :lastname, :status)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    binding.pry
    @user = User.new
  end

  def show 
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save 
      flash[:messages] = "Successfully create User, please login..."
    else
      flash[:messages] = @user.errors.full_messages.join(', ')
    end
    redirect_to signup_path 
  end

  def countries
    @countries = Country.pluck(:name, :id)
  end 

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :country)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_heading.html.erb
<header>
  <div class="container">
    <nav>
      <ul class="nav_ul">
        <li class="nav_li">
          <%= link_to root_path, class: '' do %>
            <% image_tag('rails.png', class: 'home-icon', title: 'Go To Home Page') %>
          <% end %>
        </li>

        <li class="nav_li">
          <%= link_to banks_path do %>
            <%= image_tag('bank.jpeg', class: 'bank-icon', title: 'Go to Bank Page') %>
          <% end %>
        </li>

        <li class="nav_li">
          <%= link_to orders_path do %>
            <%= image_tag('order.jpeg', class: 'order-icon', title: 'Go to Order Page') %>
          <% end %>
        </li>
      </ul>
    </nav>
  </div>
</header>
 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog Application</title>
    <%= favicon_link_tag 'favicon.png' %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= render partial: 'layouts/heading' %>
    <%= yield %>
  </body>
</html>

app/views/layouts/banks.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApplication</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "main", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "main" %>
  </head>
  <body>
    <%= render partial: 'layouts/heading' %>
    <%= yield %>
    <%= image_tag('rails.png', class: 'rails-pages') %><br>
    <%= link_to "w3school",  'https://www.w3schools.com/' %><br><br>
    <%= image_tag "diploma.jpg", {height: 100}  %><br>
    <%= image_tag "images_1.jpg", {height: 100}  %><br>
  </body>
</html>

app/views/layouts/my_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <style>
      /* Email styles need to be inline */
    </style>
  </head>

  <body>
    <h1 style ="background-color: pink">HTML Mailer</h1>
  </body>
</html>

app/views/layouts/order_mailer.text.erb
<%= yield %>

app/views/layouts/sessions.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog Application</title>
    <%= favicon_link_tag 'favicon.png' %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/special.html.erb
<h1>Nancy</h1>

app/views/layouts/users.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog Application</title>
    <%= favicon_link_tag 'favicon.png' %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>